### ISSUE TITLE
No display on 5" DPI

### ISSUE THREAD

**Issue by kiasarecool** [eleclab-rpi/5INCH_DPI_DISPLAY#1]
Followed the instructions provided, even completely replaced config.txt... no display, please advise. 
<img>https://www.kcplantfactory.com/wp-content/uploads/2022/06/IMG_0546-scaled.jpg</img>

Issue found to be conflicting with pisugar

**Comment by eleclab-rpi** [comment]
Sorry for the inconvenience, do you have a 5" DPI display? In addition to adding parameters to config.txt, put eleclab-dpi5inch.dtbo in the /boot/overlays/ directory.

The parameters to be added in config.txt are as follows:

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
gpio=0-9=a2
gpio=12-17=a2
gpio=20-25=a2
dtoverlay=dpi24
enable_dpi_lcd=1
display_default_lcd=1
extra_transpose_buffer=2
dpi_group=2
dpi_mode=87
dpi_output_format=0x78216
dpi_timings=480 0 60 2 55 854 0 16 2 22 0 0 0 60 0 32000000 6 #for no rotate or for display_rotate=2
#dpi_timings=480 0 60 2 55 856 0 16 2 22 0 0 0 60 0 32000000 6 #for display_rotate=1,3
dtoverlay=eleclab-dpi5inch
#display_rotate=1 #1:90;2:180;3:270 , Need to modify 40-libinput.conf



***@***.***
 
From: kiasarecool
Date: 2022-06-02 06:26
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: Subscribed
Subject: [eleclab-rpi/5INCH_DPI_DISPLAY] No display on 5" DPI (Issue #1)
Followed the instructions provided, even completely replaced config.txt... no display, please advise.

**Comment by kiasarecool** [comment]
Ok so I have found out that the issue is with this model of UPS battery, when attached in combination with the screen the display is color bars as shown in the picture link above... (The UPS https://www.amazon.com/Portable-Platform-Raspberry-Accessories-handhold/dp/B097RCFHD2 )

I changed to the older model PiSugar2 and it is working fine now besides a few minor things while using in landscape mode, video in VLC does not display correctly, it is limited to 480px wide and fullscreen does not fill the screen, will add pictures soon.

**Comment by eleclab-rpi** [comment]
What a great news, I thought you could share it.
I guess video playback is not necessarily going to be full screen when displayed on different resolution displays.



***@***.***
 
From: kiasarecool
Date: 2022-06-02 10:37
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] No display on 5" DPI (Issue #1)
Ok so I have found out that the issue is with this model of UPS battery, when attached in combination with the screen the display is color bars as shown in the picture link above... (The UPS https://www.amazon.com/Portable-Platform-Raspberry-Accessories-handhold/dp/B097RCFHD2 )
I changed to the older model PiSugar2 and it is working fine now besides a few minor things while using in landscape mode, video in VLC does not display correctly, it is limited to 480px wide and fullscreen does not fill the screen, will add pictures soon.

**Comment by kiasarecool** [comment]
The video issue seems to be isolated to VLC, I will keep working on that but before I close this do you have any advice on getting kodi to run on this screen, it (kodi) just seems to crash when you launch it and kodi would be a great use for this display! (on raspberry pi os)

Overall great product, love it and will be leaving a good amazon review!

**Comment by eleclab-rpi** [comment]
What version and link of kodi are you using? I will try it too.
Would it be a bit small to play a video on a 5" 480X854 display?



***@***.***
 
From: kiasarecool
Date: 2022-06-02 10:58
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] No display on 5" DPI (Issue #1)
The video issue seems to be isolated to VLC, I will keep working on that but before I close this do you have any advice on getting kodi to run on this screen, it (kodi) just seems to crash when you launch it and kodi would be a great use for this display! (on raspberry pi os)
Overall great product, love it and will be leaving a good amazon review!

**Comment by kiasarecool** [comment]
Kodi 19.1 on raspberry pi os with display_rotate=1
When I boot to CLI instead of desktop and try to launch kodi from the command line it says "can't load gui" 
Thank You!
p.s. I am upgrading from a 4" hyperpixel display so it feels huge :)

Edit: Video played from my site https://www.kcpcdr.com/sp/ plays 100% perfect... looking more and more like its a Kodi issue.

Edit2: Found an iptv player that works with this great display
Hypnotix!
wget https://github.com/linuxmint/hypnotix/releases/download/1.1/hypnotix_1.1_all.deb

sudo apt install ./hypnotix_1.1_all.deb

**Comment by eleclab-rpi** [comment]
OK, I like that Volumio installed a 1T SSD to play the music library. Now I'm going to switch to Kodi, lol.



***@***.***
 
From: kiasarecool
Date: 2022-06-02 11:11
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] No display on 5" DPI (Issue #1)
Kodi 19.1 on raspberry pi os with display_rotate=1
When I boot to CLI instead of desktop and try to launch kodi from the command line it says "can't load gui"
Thank You!

**Comment by kiasarecool** [comment]
The issue with VLC and many other apps seems to be
`This is one of those issues over a hybrid rendering system.
VLC in full screen drops back to using MMAL for rendering, however X's screen rotation is hidden from apps under most conditions. VLC therefore doesn't necessarily know that the screen is rotated, and renders the video as normal.`
[https://forums.raspberrypi.com/viewtopic.php?t=267438](url)

**Comment by eleclab-rpi** [comment]
Oh, thanks for the reminder, the new 7.4" 1280x400 rectangular display is on the shelf, and I'll send you one if you're interested in trying it out.

https://www.amazon.com/dp/B09YJ37SBH?ref=myi_title_dp&th=1


***@***.***
 
From: kiasarecool
Date: 2022-06-03 12:20
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] No display on 5" DPI (Issue #1)
The issue with VLC and many other apps seems to be
This is one of those issues over a hybrid rendering system. VLC in full screen drops back to using MMAL for rendering, however X's screen rotation is hidden from apps under most conditions. VLC therefore doesn't necessarily know that the screen is rotated, and renders the video as normal.
https://forums.raspberrypi.com/viewtopic.php?t=267438

**Comment by kiasarecool** [comment]
I would definitely be interested in that, I messaged you on amazon.

**Comment by eleclab-rpi** [comment]
Please send your address and phone number again, and I will manually create a shipping order to you when the available inventory is not 0.



***@***.***
 
From: kiasarecool
Date: 2022-06-04 07:54
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] No display on 5" DPI (Issue #1)
Closed #1 as completed.

**Comment by kiasarecool** [comment]
Shipping address is 204 13 Ave N, Greenwood, MO 64034 and my phone number
is 816-898-7207 (USA +1)

**Comment by eleclab-rpi** [comment]
Several months have passed, please check the order below!




***@***.***
 
From: kiasarecool
Date: 2022-10-11 22:41
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] No display on 5" DPI (Issue #1)
Shipping address is 204 13 Ave N, Greenwood, MO 64034 and my phone number
is 816-898-7207 (USA +1)

**Comment by kiasarecool** [comment]
I was wondering why you had asked for the address again? I am currently
working on the next video with the last screen I got, I will send it you
you when I am finished.

**Comment by eleclab-rpi** [comment]
Sorry, I don't remember, this is the email from June 4th. I look forward to your work very much.



***@***.***
 
From: kiasarecool
Date: 2022-10-13 07:05
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] No display on 5" DPI (Issue #1)
I was wondering why you had asked for the address again? I am currently
working on the next video with the last screen I got, I will send it you
you when I am finished.
