### ISSUE TITLE
horizontal  touch screen not working

### ISSUE THREAD

**Issue by Harrball76** [eleclab-rpi/5INCH_DPI_DISPLAY#4]
I have done a fresh install on a PI 3B+ and when i set the screen to horizontal the touch screen is reversed 

to get the screen to even  go horizontal i had to change display_rotate to display__lcd_rotate=1 to make the screen rotate.

[all]
#dtoverlay=vc4-fkms-v3d
gpio=0-9=a2
gpio=12-17=a2
gpio=20-25=a2
dtoverlay=dpi24
enable_dpi_lcd=1
display_default_lcd=1
extra_transpose_buffer=2
dpi_group=2
dpi_mode=87
dpi_output_format=0x78216
#dpi_timings=480 0 60 2 55 854 0 16 2 22 0 0 0 60 0 32000000 6  #for no rotate or for display_rotate=2
dpi_timings=480 0 60 2 55 856 0 16 2 22 0 0 0 60 0 32000000 6   #for  display_rotate=1,3
dtoverlay=eleclab-dpi5inch
#lcd_rotate=2
#display_rotate=2  #1：90；2: 180； 3: 270   , Need to modify 40-libinput.conf

# For 90 degree rotation (top to right):
display_lcd_rotate=1
#dtoverlay=rpi-ft5406,touchscreen-swapped-x-y=1,touchscreen-inverted-x=1 

___________________________________________________________________________________________________________________________
I have under 40-libinput.conf
Section "InputClass"
        Identifier "libinput touchscreen catchall"
        MatchIsTouchscreen "on"
#       Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1” 
        MatchDevicePath "/dev/input/event*"
        Option "SwapAxes" "1"
        Option "InvertX" "true"
        Driver "libinput"
EndSection

when i remove the # and reboot the screen goes to cli prompt when I edit the file screen returns to the desktop but the touch screen is reversed.

**Comment by eleclab-rpi** [comment]
Dear user, the rotation of the touch screen has three parameters corresponding to three angles. Please try it:
Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1” #touchscreen rotate 90
Option “CalibrationMatrix” “-1 0 1 0 -1 1 0 0 1” #touchscreen rotate 180
Option “CalibrationMatrix” “0 -1 1 1 0 0 0 0 1” #touchscreen rotate 270
Best Wishes!



***@***.***
 
From: Harrball76
Date: 2024-03-28 00:06
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: Subscribed
Subject: [eleclab-rpi/5INCH_DPI_DISPLAY] horizontal touch screen not working (Issue #4)
I have done a fresh install on a PI 3B+ and when i set the screen to horizontal the touch screen is reversed
to get the screen to even go horizontal i had to change display_rotate to display__lcd_rotate=1 to make the screen rotate.
[all]
#dtoverlay=vc4-fkms-v3d
gpio=0-9=a2
gpio=12-17=a2
gpio=20-25=a2
dtoverlay=dpi24
enable_dpi_lcd=1
display_default_lcd=1
extra_transpose_buffer=2
dpi_group=2
dpi_mode=87
dpi_output_format=0x78216
#dpi_timings=480 0 60 2 55 854 0 16 2 22 0 0 0 60 0 32000000 6 #for no rotate or for display_rotate=2
dpi_timings=480 0 60 2 55 856 0 16 2 22 0 0 0 60 0 32000000 6 #for display_rotate=1,3
dtoverlay=eleclab-dpi5inch
#lcd_rotate=2
#display_rotate=2 #1：90；2: 180； 3: 270 , Need to modify 40-libinput.conf
For 90 degree rotation (top to right):
display_lcd_rotate=1
#dtoverlay=rpi-ft5406,touchscreen-swapped-x-y=1,touchscreen-inverted-x=1


I have under 40-libinput.conf
Section "InputClass"
Identifier "libinput touchscreen catchall"
MatchIsTouchscreen "on"
Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1”
    MatchDevicePath "/dev/input/event*"
    Option "SwapAxes" "1"
    Option "InvertX" "true"
    Driver "libinput"

EndSection
when i remove the # and reboot the screen goes to cli prompt when I edit the file screen returns to the desktop but the touch screen is reversed.

**Comment by eleclab-rpi** [comment]
So which system among buster/bullseye/bookworm are you using for RPI3 now? I can use the same scenario.



***@***.***
 
From: Harrball76
Date: 2024-03-28 00:06
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: Subscribed
Subject: [eleclab-rpi/5INCH_DPI_DISPLAY] horizontal touch screen not working (Issue #4)
I have done a fresh install on a PI 3B+ and when i set the screen to horizontal the touch screen is reversed
to get the screen to even go horizontal i had to change display_rotate to display__lcd_rotate=1 to make the screen rotate.
[all]
#dtoverlay=vc4-fkms-v3d
gpio=0-9=a2
gpio=12-17=a2
gpio=20-25=a2
dtoverlay=dpi24
enable_dpi_lcd=1
display_default_lcd=1
extra_transpose_buffer=2
dpi_group=2
dpi_mode=87
dpi_output_format=0x78216
#dpi_timings=480 0 60 2 55 854 0 16 2 22 0 0 0 60 0 32000000 6 #for no rotate or for display_rotate=2
dpi_timings=480 0 60 2 55 856 0 16 2 22 0 0 0 60 0 32000000 6 #for display_rotate=1,3
dtoverlay=eleclab-dpi5inch
#lcd_rotate=2
#display_rotate=2 #1：90；2: 180； 3: 270 , Need to modify 40-libinput.conf
For 90 degree rotation (top to right):
display_lcd_rotate=1
#dtoverlay=rpi-ft5406,touchscreen-swapped-x-y=1,touchscreen-inverted-x=1


I have under 40-libinput.conf
Section "InputClass"
Identifier "libinput touchscreen catchall"
MatchIsTouchscreen "on"
Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1”
    MatchDevicePath "/dev/input/event*"
    Option "SwapAxes" "1"
    Option "InvertX" "true"
    Driver "libinput"

EndSection
when i remove the # and reboot the screen goes to cli prompt when I edit the file screen returns to the desktop but the touch screen is reversed.

**Comment by Harrball76** [comment]
I am using Buster on a pi3. I use the raspberry pi image installer updated. Everything followed the directions and I cannot get the touch screen to work correctly. Horizontally

**Comment by eleclab-rpi** [comment]
OK, the buster version I have here is 2022-09-22-raspios-buster-armhf. Please take a photo of the landscape you ultimately want to use. Then I will know whether you have rotated 90 degrees or 270 degrees.



***@***.***
 
From: Harrball76
Date: 2024-03-29 21:48
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] horizontal touch screen not working (Issue #4)
I am using Buster on a pi3. I use the raspberry pi image installer updated. Everything followed the directions and I cannot get the touch screen to work correctly. Horizontally

**Comment by Harrball76** [comment]
![PXL_20240329_141216884.jpg](https://github.com/eleclab-rpi/5INCH_DPI_DISPLAY/assets/122741110/e0355079-e238-48bd-a659-3718a17d5aad)

**Comment by eleclab-rpi** [comment]
1.Configure as follows in config.txt:

[all]
#dtoverlay=vc4-fkms-v3d
gpio=0-9=a2
gpio=12-17=a2
gpio=20-25=a2
dtoverlay=dpi24
enable_dpi_lcd=1
display_default_lcd=1
extra_transpose_buffer=2
dpi_group=2
dpi_mode=87
dpi_output_format=0x78216
#dpi_timings=480 0 60 2 55 854 0 16 2 22 0 0 0 60 0 32000000 6 #for display_rotate=0,2
dpi_timings=480 0 60 2 55 856 0 16 2 22 0 0 0 60 0 32000000 6 #for  display_rotate=1,3
dtoverlay=eleclab-dpi5inch
display_rotate=1  #1：90；2: 180； 3: 270   , Need to modify 40-libinput.conf

2. Plug in the mouse and keyboard on the Raspberry Pi after starting buster/bullesys on the Raspberry Pi, enter the following command in the running terminal:

sudo apt-get install xserver-xorg-input-libinput     
sudo mkdir /etc/X11/xorg.conf.d
sudo cp /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/

3. Edit /etc/X11/xorg.conf.d/40-libinput-conf and add a line:
    Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1” 


***@***.***
 
From: Harrball76
Date: 2024-03-29 22:13
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] horizontal touch screen not working (Issue #4)
PXL_20240329_141216884.jpg (view on web)

**Comment by eleclab-rpi** [comment]
4. Enter sync
5. Enter reboot
6. Now the touch and display can match



***@***.***
 
From: Harrball76
Date: 2024-03-29 22:13
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] horizontal touch screen not working (Issue #4)
PXL_20240329_141216884.jpg (view on web)

**Comment by Harrball76** [comment]
![PXL_20240402_130007366.jpg](https://github.com/eleclab-rpi/5INCH_DPI_DISPLAY/assets/122741110/711872e2-57a1-40ff-84c0-bdc80e0c8631)



Still crashing

**Comment by eleclab-rpi** [comment]
HI, Your Raspberry Pi doesn’t enter the desktop? This issue is not related to the display and touch rotation. The latest buster version we use is 2022-09-22-raspios-buster-armhf.img.xz. We have only tested 5" 480x854 display rotation on RPI1,2,3,4+buster/bullseye. There are still some issues with bookworm, and today we submitted an issue with 10.1" HDMI 2560x1600. All our other HDMI displays have to be re-adapted, which is very troublesome.



***@***.***
 
From: Harrball76
Date: 2024-04-02 21:01
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] horizontal touch screen not working (Issue #4)
PXL_20240402_130007366.jpg (view on web)
Still crashing

**Comment by Harrball76** [comment]
Ok if I comment out 

Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1”

The desktop will return just so you know

Thanks for your help

**Comment by eleclab-rpi** [comment]
Hi, try burning another buster. My attachments were copied directly from the TF card.
Good Luck!


***@***.***
 
From: Harrball76
Date: 2024-04-02 23:53
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] horizontal touch screen not working (Issue #4)
Ok if I comment out
Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1”
The desktop will return just so you know
Thanks for your help

**Comment by Harrball76** [comment]
I found the issue in the 40-libinput-conf 
they changed the command from CalibrationMatrix to TransformationMatrix

sample:
Section "InputClass"
        Identifier "libinput touchscreen catchall"
        MatchIsTouchscreen "on"
        Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1”
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"

All is working now Thanks for your help

**Comment by eleclab-rpi** [comment]
Thanks a lot, got it , I will use your suggestions.



***@***.***
 
From: Harrball76
Date: 2024-04-05 00:13
To: eleclab-rpi/5INCH_DPI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5INCH_DPI_DISPLAY] horizontal touch screen not working (Issue #4)
I found the issue in the 40-libinput-conf
they changed the command from CalibrationMatrix to TransformationMatrix
sample:
Section "InputClass"
Identifier "libinput touchscreen catchall"
MatchIsTouchscreen "on"
Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1”
MatchDevicePath "/dev/input/event*"
Driver "libinput"
All is working now Thanks for your help

**Comment by chris-wei-17** [comment]
@Harrball76 could you share again the edits you made to your files?  I am on a 4b with a fresh RPi OS Bookworm install and am getting just a black screen.  Hoping that your configuration might also work for me

**Comment by Harrball76** [comment]
in the /boot/config. txt  at the bottom I have

[all]
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
gpio=0-9=a2
gpio=12-17=a2
gpio=20-25=a2
dtoverlay=dpi24
enable_dpi_lcd=1
display_default_lcd=1
extra_transpose_buffer=2
dpi_group=2
dpi_mode=87
dpi_output_format=0x78216
#dpi_timings=480 0 60 2 55 854 0 16 2 22 0 0 0 60 0 32000000 6  #for no rotate or for display_rotate=2
dpi_timings=480 0 60 2 55 856 0 16 2 22 0 0 0 60 0 32000000 6
#for  display_rotate=1,3
dtoverlay=eleclab-dpi5inch
display_rotate=1
#1：90；2: 180； 3: 270   , Need to modify 40-libinput.conf
______________________________________________________________________________________________________________________________________

in the /etc/X11/xorg.conf.d/40-libinput.conf  i changed the CalibrationMatrix to TransformationMatrix
this was causing the desktop not to load 

Section "InputClass"
        Identifier "libinput touchscreen catchall"
        MatchIsTouchscreen "on"
        Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1” 
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection
